//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplyBrand.SocialMonitor.Controller.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.ISimplyReportService")]
    public interface ISimplyReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimplyReportService/GeneratePDF", ReplyAction="http://tempuri.org/ISimplyReportService/GeneratePDFResponse")]
        string GeneratePDF(int sysUserId, string reportStarttime, string reportEndTime, SimplyBrand.SocialMonitor.Business.Utility.EnumReportType type, bool isSysGen, string platforms, string keywordFamilyIDs, string emotionvalues);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimplyReportServiceChannel : SimplyBrand.SocialMonitor.Controller.ReportService.ISimplyReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplyReportServiceClient : System.ServiceModel.ClientBase<SimplyBrand.SocialMonitor.Controller.ReportService.ISimplyReportService>, SimplyBrand.SocialMonitor.Controller.ReportService.ISimplyReportService {
        
        public SimplyReportServiceClient() {
        }
        
        public SimplyReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplyReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplyReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplyReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GeneratePDF(int sysUserId, string reportStarttime, string reportEndTime, SimplyBrand.SocialMonitor.Business.Utility.EnumReportType type, bool isSysGen, string platforms, string keywordFamilyIDs, string emotionvalues) {
            return base.Channel.GeneratePDF(sysUserId, reportStarttime, reportEndTime, type, isSysGen, platforms, keywordFamilyIDs, emotionvalues);
        }
    }
}
